services:
  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=spring_modulith'
      - 'POSTGRES_PASSWORD=modulith1'
      - 'POSTGRES_USER=modulith1'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
